# Generated by Django 2.1.1 on 2019-04-17 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_auto_20190306_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=1500),
        ),
    ]
