# Generated by Django 2.1.1 on 2019-03-06 18:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=80)),
                ('BookId', models.CharField(max_length=100, unique=True)),
                ('BookName', models.CharField(max_length=200, unique=True)),
                ('Index', models.IntegerField()),
                ('Price', models.FloatField()),
                ('Quantity', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fullname', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=80, unique=True)),
                ('password', models.CharField(max_length=15)),
                ('phone', models.CharField(max_length=20)),
                ('register_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
