# Generated by Django 2.1.1 on 2019-03-09 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_auto_20190306_2348'),
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='BookId',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='BookName',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='Index',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='Price',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='email',
        ),
        migrations.AddField(
            model_name='cart',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='company.Category'),
        ),
        migrations.AddField(
            model_name='cart',
            name='company',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='company.Company'),
        ),
        migrations.AddField(
            model_name='cart',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='image',
            field=models.ImageField(blank=True, upload_to='products/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='cart',
            name='name',
            field=models.CharField(db_index=True, default='AI', max_length=100),
        ),
        migrations.AddField(
            model_name='cart',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='cart',
            name='slug',
            field=models.SlugField(default='None<django.db.models.fields.CharField>', max_length=150),
        ),
        migrations.AlterField(
            model_name='cart',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
