# Generated by Django 2.1.1 on 2019-03-09 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20190309_0806'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='Index',
            field=models.IntegerField(default='-1'),
        ),
        migrations.AddField(
            model_name='cart',
            name='email',
            field=models.CharField(default='Ai@gmail.com', max_length=80),
        ),
    ]
