# Generated by Django 2.1.1 on 2019-03-27 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_register_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='image',
            field=models.ImageField(blank=True, upload_to='user/%Y/%m/%d'),
        ),
    ]
