# Generated by Django 2.1.1 on 2019-03-29 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0013_register_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='bill',
        ),
        migrations.DeleteModel(
            name='Log',
        ),
    ]
