# Generated by Django 2.1.1 on 2019-04-15 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0019_bill_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
