# Generated by Django 2.1.1 on 2019-04-16 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0021_auto_20190416_0344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='bill_id',
            field=models.IntegerField(default=-1),
        ),
    ]
