# Generated by Django 2.1.1 on 2019-04-16 02:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0022_auto_20190416_0754'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='log',
            name='bill_id',
            field=models.IntegerField(default=0),
        ),
    ]
