# Generated by Django 2.1.1 on 2019-04-17 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0005_auto_20190417_0826'),
        ('login', '0023_auto_20190416_0804'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stocks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Register')),
            ],
        ),
    ]
